### ISSUE TITLE
We want mobile! We want mobile!!

### ISSUE THREAD

**Issue by johndoe-syskeyonyou** [crunchytop/crunchytop#1]
PLZ MAKE CRUNCHYTOP FOR IPHONE

**Comment by 2qbruh** [comment]
Hi,

Seeing as you are on iOS, Electron is **not** available outside of Windows, macOS, or Linux. iOS is not
planned to be added anytime in the future, as we are a desktop software org.
Until then, use this: https://apps.apple.com/us/app/crunchyroll/id329913454 (it works for iPad and TV too 😄).

Thanks for your interest in Crunchytop,
2qbruh
